website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for 
from flask_login import login_required, current_user
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user 
from flask import current_app

auth = Blueprint('auth',__name__) 

@auth.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.get_by_email(email)
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True, fresh=True) # Force a fresh login
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=__name__)

@auth.route('/logout')
@login_required
def logout(): 
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods = ['GET', 'POST'])
def sign_up(): 
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.get_by_email(email)
        if user: 
            flash('Email already exists.', category='error')
        
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else: 
            hashed_password = generate_password_hash(password1, method='sha256')
            new_user = User(id=id, email=email, password=hashed_password, first_name=first_name)
            new_user.save()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            #return redirect(url_for('views.home'))            
    
    return render_template("sign_up.html", user=current_user)


@auth.route('/delete', methods=['POST'])
@login_required
def delete_user():
    password = request.form.get('password')

    # Reload the user data from the database
    user_to_delete = User.get_by_id(current_user.id)
    login_user(user_to_delete, remember=True, fresh=True)

    if not check_password_hash(user_to_delete.password, password):
        flash('Incorrect password, try again', category='error')
        return redirect(url_for('views.home'))

    print("User to delete: ", user_to_delete) # Debugging statement

    if user_to_delete is not None:
        user_to_delete.delete()
        logout_user()
        flash('Your account has been deleted.', category='success')
    else:
        flash('User not found.', category='error')

    return redirect(url_for('auth.login'))


@auth.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
   if request.method == 'POST':
       old_password = request.form.get('current_password')
       new_password = request.form.get('new_password')
       confirm_password = request.form.get('new_password_confirm')


       if not old_password or not new_password or not confirm_password:
           flash('Please fill out all fields', category='error')
           return redirect(url_for('auth.change_password'))


       if new_password != confirm_password:
           flash('New passwords do not match', category='error')
           return redirect(url_for('auth.change_password'))


       if not check_password_hash(current_user.password, old_password):
           flash('Old password is incorrect', category='error')
           return redirect(url_for('auth.change_password'))


       new_password_hash = generate_password_hash(new_password, method='sha256')


       # You need to setup your database connection and put it into the app's config under the key 'DATABASE_CONNECTION'
       conn = current_app.config['DATABASE_CONNECTION']
       cur = conn.cursor()
       cur.execute("UPDATE users SET password = %s WHERE id = %s", (new_password_hash, current_user.id))
       conn.commit()


       flash('Password updated successfully', category='success')
       return redirect(url_for('views.home'))


   return render_template('change_password.html')

website/templates/base.html
<!DOCTYPE html>
<html>
 <head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1" />
   <link
     rel="stylesheet"
     href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
     integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
     crossorigin="anonymous"
   />
   <link
     rel="stylesheet"
     href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
     crossorigin="anonymous"
   />


   <title>{% block title %}Home{% endblock %}</title>
 </head>
 <body>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <button
       class="navbar-toggler"
       type="button"
       data-toggle="collapse"
       data-target="#navbar"
     >
       <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbar">
       <div class="navbar-nav">
         <a class="nav-item nav-link" id="home" href="/">Home</a>
         <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
         <a class="nav-item nav-link" id="login" href="/login">Login</a>
         <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
         <a class="nav-item nav-link" id="change_password" href="/change-password">Change Password</a>
       </div>
     </div>
   </nav>


   {% with messages = get_flashed_messages(with_categories=true) %} {% if
   messages %} {% for category, message in messages %} {% if category ==
   'error' %}
   <div class="alert alert-danger alter-dismissable fade show" role="alert">
     {{ message }}
     <button type="button" class="close" data-dismiss="alert">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
   {% else %}
   <div class="alert alert-success alter-dismissable fade show" role="alert">
     {{ message }}
     <button type="button" class="close" data-dismiss="alert">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
   {% endif %} {% endfor %} {% endif %} {% endwith %}


   <div class="container">{% block content %} {% endblock %}</div>
   <script
     src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
     integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
     crossorigin="anonymous"
   ></script>
   <script
     src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
     integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
     crossorigin="anonymous"
   ></script>
   <script
     src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
     integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
     crossorigin="anonymous"
   ></script>


{% block javascript %}
   <script type="text/javascript">
     function deleteNote(noteId) {
 fetch("/delete-note", {
   method: "POST",
   body: JSON.stringify({ noteId: noteId }),
 }).then((_res) => {
   window.location.href = "/";
 });
 }
</script>
{% endblock %}
 </body>
</html>

website/templates/change_password.html
{% extends "base.html" %}
{% block title %}Change Password{% endblock %}
{% block content %}
<form method="POST">
 <h3 align="center">Change Password</h3>
 <div class="form-group">
   <label for="current_password">Current Password</label>
   <input
     type="password"
     class="form-control"
     id="current_password"
     name="current_password"
     placeholder="Enter current password"
     required
   />
 </div>
 <div class="form-group">
   <label for="new_password">New Password</label>
   <input
     type="password"
     class="form-control"
     id="new_password"
     name="new_password"
     placeholder="Enter new password"
     required
   />
 </div>
 <div class="form-group">
   <label for="new_password_confirm">Confirm New Password</label>
   <input
     type="password"
     class="form-control"
     id="new_password_confirm"
     name="new_password_confirm"
     placeholder="Confirm new password"
     required
   />
 </div>
 <br />
 <button type="submit" class="btn btn-primary">Change Password</button>
</form>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}IEM Database{% endblock %}

{% block content %}

<h1 style="text-align: center; padding-bottom: 20px;">IEM Database</h1>
<form method="POST" id="searchForm">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <div class="d-flex">
            {{ form.search_term(class="form-control", placeholder="Example: Apple AirPods Pro 2") }}
            {{ form.submit(class="btn btn-primary") }}
        </div>
        <div class="d-flex" id="compareDiv" style="display: none; padding-top: 5px;">
            {% if show_compare_search %}
            {{ form.compare_term(class="form-control", placeholder="Compare (Optional)") }}
            {% endif %}
        </div>
    </div>
</form>

<script>
document.getElementById('searchForm').addEventListener('submit', function() {
    document.getElementById('compareDiv').style.display = 'block';
});
</script>

<body> 
    {% if plot_file %}
    <div style="text-align: center; padding-top: 20px;">
        <img src="{{ url_for('static', filename=plot_file) }}" alt="plot" style="max-width: 100%;">
    </div>
    {% endif %}
</body>

{% if search_results %}

<div style="padding-top: 20px;">
    <h2>Search Results:</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>IEM Name</th>
                <th># of files</th>
                <th>Average Pref. %</th>
                <th>Avg. Error</th>
                <th>Slope of Error</th>
                <th>STDEV</th>
                <th>Variance</th>
                <th>Highest Pref. %</th>
                <th>Lowest Pref. %</th>
            </tr>
        </thead>
        <tbody>
            {% for result in search_results %}
            <tr>
                {% for column in result %}
                <td>
                    {% if column is number %}
                        {{ column|round(3) }}
                    {% else %}
                        {{ column }}
                    {% endif %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% if contributors %}

<h2>Contributors:</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Contributor</th>
            <th>Credit</th>
        </tr>
    </thead>
    <tbody>
        {% for contributor in contributors %}
        <tr>
            <td>{{ contributor[0] }}</td>
            <td>{{ contributor[1] }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <form method="POST" action="{{ url_for('auth.delete_user') }}">
      <h3 align="center">Delete Account</h3>
      <div class="form-group">
          <label for="password">Confirm Password</label>
          <input
              type="password"
              class="form-control"
              id="password"
              name="password"
              placeholder="Enter password to confirm deletion"
          />
      </div>
      <br />
      <button type="submit" class="btn btn-danger">Delete Account</button>
  </form>
    {% endblock %}

  

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}